name = "jadwali"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
minify = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "jadwali-db"
database_id = "0ab9fae0-8b3b-423d-8ae3-96d68dc2c985"
