name = "jadwali"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
minify = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
GOOGLE_CLIENT_ID = "557377504260-r8b419gcjdtbta4hbj7v768fbeqqujsv.apps.googleusercontent.com"
NEXT_PUBLIC_APP_URL = "https://jadwali.ai"
KONNECT_API_URL = "https://api.konnect.network/api/v2"
PAYMEE_API_URL = "https://api.paymee.tn/api/v2"

[[d1_databases]]
binding = "DB"
database_name = "jadwali-db"
database_id = "0ab9fae0-8b3b-423d-8ae3-96d68dc2c985"
